name: Update Blog Posts
on:
  schedule:
    - cron: '0 0 * * 1' # Every Monday at midnight
  workflow_dispatch: # Manual trigger

jobs:
  update-blog-posts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Update README with latest blog posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: 4
          feed_list: "https://medium.com/feed/@yusufarbc"
          comment_tag_name: "BLOG-POST-LIST"
          
      - name: Commit and push if changed
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "Updated blog posts" && git push)
