name: User Statistician Stats

on:
  push:
    branches: ["main"]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Generate the user stats image
        uses: cicirello/user-statistician@v1
        with:
          colors: dark-dimmed
          image-title: Yusuf's GitHub Stats
          output-path: profile/stats.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
